apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-vault-issuer
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: ./demo/flux/apps/cert-issuer/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
