apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin
  namespace: httpbin
spec:
  dependsOn:
    - name: ztunnel
      namespace: istio-system
  interval: "5m"
  install:
    createNamespace: true
  chart:
    spec:
      chart: httpbin
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: matheusfm
        namespace: httpbin
      interval: 12h
  values: {}
