apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
    - name: istio-cni
  interval: "5m"
  chart:
    spec:
      chart: istiod
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
