apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  interval: "5m"
  install:
    createNamespace: true
  chart:
    spec:
      chart: istiod
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
    pilot:
      env:
        PILOT_ENABLE_ALPHA_GATEWAY_API: true
