apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: "5m"
  chart:
    spec:
      chart: base
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values: {}
