apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  interval: "5m"
  install:
    createNamespace: true
  chart:
    spec:
      chart: cni
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
    cni:
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
      cniBinDir: /bin
