apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - istio-namespace.yaml
  - istio-repository.yaml
  - istio-base-release.yaml
  - istio-cni-release.yaml
  - istiod-release.yaml
  - ztunnel-release.yaml
