apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # gateway api resources (experimental - allows to use TCPRoute, TLSRoute, etc).
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
  # istio ambient mode setup
  - istio-namespace.yaml
  - istio-repository.yaml
  - istio-base-release.yaml
  - istio-cni-release.yaml
  - istiod-release.yaml
  - ztunnel-release.yaml
  # kiali setup
  - https://raw.githubusercontent.com/istio/istio/release-1.23/samples/addons/prometheus.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.23/samples/addons/kiali.yaml
  # infra gateway
  - infra-gateway-namespace.yaml
  - infra-gateway.yaml
  # kiali route
  - istio-kiali-httproute.yaml
  # app
  - httpbin-namespace.yaml
  - matheusfm-repository.yaml
  - httpbin-release.yaml
  - httpbin-httproute.yaml
