apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: "5m"
  install:
    createNamespace: true
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
  values:
    global:
      networkPolicy:
        enabled: false
      postgresql:
        auth:
          postgresPassword: postgres
          username: demo
          password: demo
          database: demo
