apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
    - name: istio-cni
    - name: istiod
  interval: "5m"
  install:
    createNamespace: true
  chart:
    spec:
      chart: ztunnel
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values: {}
