apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/cluster-local
    server: http://vault:8200
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/jwt
        serviceAccountRef:
          name: cert-manager
