apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: gateway-demo
servers: 1
agents: 2
image: rancher/k3s:v1.31.1-k3s1
ports:
  - port: 8080-8100:80-100
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
