apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Hello</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bye-config
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Bye</h1>
    </body>
    </html>
