apiVersion: v1
kind: Pod
metadata:
  name: nginx-bye
  namespace: nginx-demo
  labels:
    app: nginx-bye
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
    - name: html
      configMap:
        name: bye-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-bye-service
  namespace: nginx-demo
spec:
  selector:
    app: nginx-bye
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
